
project_id = "hntsrkacolpseqnyidis"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.finnhub-market-data]
verify_jwt = false
