project_id = "hntsrkacolpseqnyidis"

[functions.execute-trade]
verify_jwt = true

[functions.portfolio-analytics]
verify_jwt = true

[functions.liquidation-check]
verify_jwt = true

[functions.trading-engine]
verify_jwt = true

[functions.risk-management]
verify_jwt = true
