name: Supabase Schema Sync

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  supabase-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Supabase CLI
        run: |
          rm -rf supabase
          curl -L https://github.com/supabase/cli/releases/download/v2.26.9/supabase_linux_amd64.tar.gz -o supabase.tar.gz
          tar -xzf supabase.tar.gz
          sudo mv supabase /usr/local/bin/supabase
          supabase --version
      - name: Repair Supabase Migration History
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          supabase migration repair --status reverted 00000000000000 || true
          supabase migration repair --status reverted 20250620060000 || true
          supabase migration repair --status reverted 20250620072210 || true
          supabase migration repair --status reverted 20250620072945 || true
          supabase migration repair --status reverted 20250620080000 || true
          supabase migration repair --status reverted 20250625 || true
          supabase migration repair --status reverted 20250625134815 || true
      - name: Supabase DB Pull (Validate Schema)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "SUPABASE_DB_URL is not set. Please add it to your repository secrets." >&2
            exit 1
          fi
          supabase db pull --db-url "$SUPABASE_DB_URL"
